[tool.poetry]
name = "stlite-server"
version = "0.1.0"
description = ""
authors = ["Yuichiro Tachibana (Tsuchiya) <t.yic.yt@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.10, <3.12"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
requests = "^2.31.0"
black = "^24.3.0"
flake8 = "^7.0.0"
isort = "^5.13.2"
mypy = "^1.9.0"
streamlit-aggrid = "^1.0.1"
pandas-stubs = "^2.2.1.240316"
matplotlib = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"

[tool.mypy]
check_untyped_defs = true
mypy_path = "../../../../streamlit/lib"

[[tool.mypy.overrides]]
module = ["streamlit", "streamlit.*"]
ignore_errors = true

[[tool.mypy.overrides]]
module = ["pyodide", "pyodide.*", "matplotlib", "st_aggrid"]
ignore_missing_imports = true
