[tool.poetry]
name = "stlite-server"
version = "0.1.0"
description = ""
authors = ["Yuichiro Tachibana (Tsuchiya) <t.yic.yt@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
requests = "^2.32.3"
streamlit-aggrid = "^1.0.5"
pandas-stubs = "^2.2.2.240603"
matplotlib = "^3.9.1"
ruff = "^0.5.6"
pyodide-py = "^0.26.1"
pyright = "^1.1.374"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
extend-select = ["I"]

[tool.pyright]
include = ["stlite_server"]
extraPaths = ["../../../../streamlit/lib"]

[tool.pytest.ini_options]
pythonpath = "../../../../streamlit/lib"
testpaths = [
    "stlite_server_tests",  # To import the `tests` module in the `streamlit/lib` directory, use a different name for a test directory.
]
