[tool.poetry]
name = "stlite-server"
version = "0.1.0"
description = ""
authors = ["Yuichiro Tachibana (Tsuchiya) <t.yic.yt@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.10, <3.12"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
requests = "^2.28.2"
black = "^23.1.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
mypy = "^1.0.1"
streamlit-aggrid = "^0.3.3"
pandas-stubs = "^1.5.3.230214"
matplotlib = "^3.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"

[tool.mypy]
check_untyped_defs = true
mypy_path = "../../../../streamlit/lib"

[[tool.mypy.overrides]]
module = ["streamlit", "streamlit.*"]
ignore_errors = true

[[tool.mypy.overrides]]
module = ["pyodide", "pyodide.*", "matplotlib", "st_aggrid"]
ignore_missing_imports = true
