inputs:
  pr-number:
    required: false
    description: "The PR number to inform. If not provided, the action will infer the PR number from the event type."
  stats-file-prefix:
    default: "package-stats."
  size-diff-warning-threshold-kib:
    default: 128

runs:
  using: "composite"
  steps:
    - name: Set up the working directory
      shell: bash
      run: |
        working_dir=${{ runner.temp }}/stats-artifacts/
        mkdir -p $working_dir
        echo "PACKAGE_STATS_WORKING_DIR=$working_dir" >> "$GITHUB_ENV"

    - name: Get the base run_id for diff
      run: |
        diff_base_branch='${{ github.event.repository.default_branch }}'
        current_workflow='${{ github.event_name == 'workflow_run' && github.event.workflow_run.name || github.workflow }}'
        run_info=$(gh run list --branch "$diff_base_branch" --workflow "$current_workflow" --status success --limit 1 --json=databaseId,headSha --jq ".[0]")
        run_id=$(echo $run_info | jq -r ".databaseId")
        commit_sha=$(echo $run_info | jq -r ".headSha")
        echo "PACKAGE_STATS_DIFF_BASE_RUN_ID=$run_id" >> $GITHUB_ENV
        echo "PACKAGE_STATS_DIFF_BASE_COMMIT_SHA=$commit_sha" >> $GITHUB_ENV
        echo "PACKAGE_STATS_DIFF_BASE_BRANCH=$diff_base_branch" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash

    - run: |
        cd "$PACKAGE_STATS_WORKING_DIR"
        npm install jszip
      shell: bash
    - name: Gather JSON files for this commit and generate a comment body
      uses: actions/github-script@v7
      env:
        RUN_ID: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.id || github.run_id }}
      with:
        result-encoding: string
        script: |
          process.chdir(process.env.PACKAGE_STATS_WORKING_DIR);

          const fs = require("fs");
          const jszip = require('jszip');
          const { spawn } = require('child_process');

          function escapeRegex(string) {
            // https://stackoverflow.com/a/3561711/13103190
            return string.replace(/[/\-\\^$*+?.()|[\]{}]/g, '\\$&');
          }

          async function loadStatArtifactContents(runId) {
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });

            const filteredArtifacts = artifacts.data.artifacts
              .map(artifact => {
                const match = artifact.name.match(new RegExp(`^(?<prefix>${escapeRegex("${{ inputs.stats-file-prefix }}")})(?<key>.+)\.json`));
                if (match == null) {
                  return null;
                }
                return { key: match.groups["key"], artifact };
              })
              .filter(a => a != null);

            const artifactContents = await Promise.all(
              filteredArtifacts.map(async ({ key, artifact }) => {
                const downloadResponse = await github.rest.actions.downloadArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                  archive_format: 'zip',
                });

                const artifactZip = await downloadResponse.data;
                const zip = await jszip.loadAsync(artifactZip);
                const artifactFile = Object.values(zip.files)[0];
                const artifactContent = await artifactFile.async('string');

                return { key, content: JSON.parse(artifactContent) };
              })
            );

            return artifactContents;
          }

          const artifactContents = await loadStatArtifactContents(process.env.RUN_ID)
          core.startGroup('Artifact contents preview')
          console.log(JSON.stringify(artifactContents, null, 2));
          core.endGroup()

          const baseArtifactContents = await loadStatArtifactContents(process.env.PACKAGE_STATS_DIFF_BASE_RUN_ID)
          core.startGroup('Base artifact contents preview')
          console.log(JSON.stringify(baseArtifactContents, null, 2));
          core.endGroup()

          const sortedContents = artifactContents.sort((a, b) => a.content.name.localeCompare(b.content.name));

          function compareStrings(str1, str2) {
            fs.writeFileSync('temp1.txt', str1);
            fs.writeFileSync('temp2.txt', str2);

            const diff = spawn(
              'diff',
              [
                // Ref: https://stackoverflow.com/a/354590/13103190
                '--new-line-format', '+%L',
                '--old-line-format', '-%L',
                '--unchanged-line-format', ' %L',
                'temp1.txt',
                'temp2.txt'
              ]
            );

            let output = '';
            diff.stdout.on('data', (data) => {
              output += data.toString();
            });

            return new Promise((resolve, reject) => {
              diff.on('close', (code) => {
                fs.unlinkSync('temp1.txt');
                fs.unlinkSync('temp2.txt');

                resolve({ isDiff: code === 0, diff: output });
              });
            });
          }

          let comment = "";
          comment +=
            `Diffs are from [\`${process.env.PACKAGE_STATS_DIFF_BASE_COMMIT_SHA.slice(0, 7)}\`](https://github.com/${{ github.repository }}/commit/${process.env.PACKAGE_STATS_DIFF_BASE_COMMIT_SHA}) ` +
            `on [\`${process.env.PACKAGE_STATS_DIFF_BASE_BRANCH}\`](https://github.com/whitphx/stlite/tree/${process.env.PACKAGE_STATS_DIFF_BASE_BRANCH})  ` +
            `(workflow run: [\`${process.env.PACKAGE_STATS_DIFF_BASE_RUN_ID}\`](https://github.com/${{ github.repository }}/actions/runs/${process.env.PACKAGE_STATS_DIFF_BASE_RUN_ID}))\n\n`;

          for (const artifactContent of sortedContents) {
            const { key, content } = artifactContent;

            const baseContent = baseArtifactContents.find(b => b.key === key)?.content;

            const sizeKiB = content.package.sizeKib;
            const baseSizeKiB = baseContent?.package?.sizeKib;
            const sizeDiffKiB = sizeKiB - baseSizeKiB;
            const shouldWarn = Math.abs(sizeDiffKiB) >= ${{ inputs.size-diff-warning-threshold-kib }};
            const sizeDiffFormatter = new Intl.NumberFormat("en-US", { signDisplay: "always" });
            const sizeDiffStr = baseSizeKiB ? `(${baseSizeKiB} kiB ${shouldWarn ? '⚠️ ' : ''}**${sizeDiffFormatter.format(sizeDiffKiB)} kiB**)` : "";

            const fileSizesCmp = await compareStrings(baseContent?.filelist?.sizes ?? "", content.filelist.sizes)

            comment += `### ${content.name}
          \`${content.package.filename}\`: ${sizeKiB} kiB ${sizeDiffStr}

          <details>
          <summary>File Tree</summary>

          \`\`\`\n${content.filelist.tree}\n\`\`\`

          </details>

          <details>
          <summary>File Sizes</summary>

          \`\`\`diff\n${fileSizesCmp.diff}\n\`\`\`

          </details>

          `;
          }
          core.startGroup('Comment preview')
          core.info(comment);
          core.endGroup()

          fs.writeFileSync('comment.txt', comment);

    - name: Post a message to Pull Request threads
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        COMMIT_SHA: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
        # When the event is `pull_request`, `github.sha` points to a temporary merge commit, so we use `github.event.pull_request.head.sha` instead. Ref: https://github.com/orgs/community/discussions/47804#discussioncomment-5026092
      with:
        script: |
          process.chdir(process.env.PACKAGE_STATS_WORKING_DIR);

          const fs = require("fs");

          const commentBody = fs.readFileSync('comment.txt');

          async function getTargetPullRequests() {
            if (process.env.PR_NUMBER) {
              return [
                (await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: process.env.PR_NUMBER,
                })).data
              ];
            }
            if (context.eventName === "pull_request") {
              return [context.payload.pull_request];
            }
            if (context.eventName === "push" || context.eventName === "workflow_run") {
              const pullRequests = (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  commit_sha: process.env.COMMIT_SHA,
                })
              ).data;
              const openPullRequests = pullRequests.filter(pr => pr.state === "open")
              return openPullRequests;
            }
            throw new Error(`Unsupported event type: ${context.eventName}`);
          }
          const targetPullRequests = await getTargetPullRequests();

          core.startGroup('Found PRs:')
          console.log(targetPullRequests)
          core.endGroup()

          const stickyCommentHeader = `<!-- Sticky Stat Comment ${process.env.COMMIT_SHA} -->\n`;

          for (const pr of targetPullRequests) {
            const title = `## Package Stats on [\`${process.env.COMMIT_SHA.slice(0, 7)}\`](${pr.html_url}/commits/${process.env.COMMIT_SHA})\n\n`;
            const commentText = title + commentBody;

            const stickyCommentText = stickyCommentHeader + commentText

            const existingComments = await github.paginate(
              github.rest.issues.listComments,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
              }
            );

            const existingComment = existingComments.find(comment =>
              comment.body.startsWith(stickyCommentHeader) && comment.user.login === 'github-actions[bot]'
            );

            if (existingComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: stickyCommentText,
              });
              core.info(`Updated comment on PR #${pr.number}`);
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: stickyCommentText,
              });
              core.info(`Created comment on PR #${pr.number}`);
            }
          }
