name: 'Initialization Action'
description: 'Common initialization steps for CI jobs'
inputs:
  python-version-file:
    description: 'Python version file to setup'
    required: false
  node-version-file:
    description: 'Node version file to setup'
    required: false
runs:
  using: "composite"
  steps:
    ## Set up Python
    - uses: actions/setup-python@v5
      with:
        python-version-file: ${{ inputs.python-version-file }}
      if: ${{ inputs.python-version-file }}

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ">0.5.17 || <0.5.17"  # 0.5.17 has an issue https://github.com/astral-sh/uv/issues/10487
        enable-cache: true
        cache-dependency-glob: |
          **/requirements*.txt
          **/uv.lock
      if: ${{ inputs.python-version-file }}

    ## Set up Node environment
    - name: Enable Corepack
      run: corepack enable
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: 'yarn'
      if: ${{ inputs.node-version-file }}

    # We require protoc >= 3.20, but Ubuntu 22.04 - the OS that these Github
    # Actions are running as of 2023.05.03 - doesn't have recent versions
    # of protoc in its package repository.
    # Ref: https://github.com/streamlit/streamlit/blob/1.23.1/.github/actions/make_init/action.yml#L47-L56
    # So we download the precompiled binary from the release page and install it,
    # following https://grpc.io/docs/protoc-installation/#install-pre-compiled-binaries-any-os
    - name: Install protoc
      run: |
        curl -LO $PB_REL/download/v3.20.3/protoc-3.20.3-linux-x86_64.zip
        unzip protoc-3.20.3-linux-x86_64.zip -d $HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      env:
        PB_REL: "https://github.com/protocolbuffers/protobuf/releases"
      shell: bash

    - name: Set up Python packages
      run: make venv
      shell: bash
      if: ${{ inputs.python-version-file }}

    - name: Set up Node packages
      run: make node_modules
      shell: bash
      if: ${{ inputs.node-version-file }}
