name: 'Initialization Action'
description: 'Common initialization steps for CI jobs'
inputs:
  python-version:
    description: 'Python version to setup'
    required: true
  node-version-file:
    description: 'Node version file to setup'
    required: true
runs:
  using: "composite"
  steps:
    ## Set up Python and Poetry environment
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # The following steps are based on https://github.com/python-poetry/poetry/blob/def1ee8f3ae00c307ca028da53d2347615c5c32b/.github/workflows/main.yml#L51-L84
    - name: Get full Python version
      id: full-python-version
      run: echo version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))") >> $GITHUB_OUTPUT
      shell: bash

    - name: Bootstrap poetry
      run: |
        curl -sL https://install.python-poetry.org | python - -y
      shell: bash

    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Configure poetry
      run: poetry config virtualenvs.in-project false
      shell: bash

    - name: Set up cache
      uses: actions/cache@v4
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('requirements*.txt') }}

    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      run: timeout 10s pip --version || rm -rf .venv
      shell: bash

    - name: Create virtualenv
      run: python -m venv .venv
      shell: bash

    ## Set up Node environment
    - uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: 'yarn'

    # We require protoc >= 3.20, but Ubuntu 22.04 - the OS that these Github
    # Actions are running as of 2023.05.03 - doesn't have recent versions
    # of protoc in its package repository.
    # Ref: https://github.com/streamlit/streamlit/blob/1.23.1/.github/actions/make_init/action.yml#L47-L56
    # So we download the precompiled binary from the release page and install it,
    # following https://grpc.io/docs/protoc-installation/#install-pre-compiled-binaries-any-os
    - name: Install protoc
      run: |
        curl -LO $PB_REL/download/v3.20.3/protoc-3.20.3-linux-x86_64.zip
        unzip protoc-3.20.3-linux-x86_64.zip -d $HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      env:
        PB_REL: "https://github.com/protocolbuffers/protobuf/releases"
      shell: bash

    - name: Set up
      run: make init
      shell: bash
