name: 'Initialization Action'
description: 'Common initialization steps for CI jobs'
inputs:
  python-version-file:
    description: 'Python version file to setup'
    required: false
  node-version-file:
    description: 'Node version file to setup'
    required: false
  install-node-modules:
    description: 'Whether to install Node.js modules using "make node_modules"'
    required: false
    default: 'true'
  protoc:
    description: 'Whether to install protoc'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    ## Set up Python
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/requirements*.txt
          **/uv.lock
      if: ${{ inputs.python-version-file }}

    ## Set up Node environment
    - name: Remove classic Yarn on Windows so that it does not conflict with Corepack.
      if: runner.os == 'Windows' && ${{ inputs.node-version-file }}
      run: npm uninstall -g yarn
      shell: bash

    - name: Enable Corepack
      run: corepack enable
      shell: bash
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ${{ inputs.node-version-file }}
      if: ${{ inputs.node-version-file }}

    # `actions/setup-node`'s cache option doesn't work well with corepack.
    - name: Get Yarn cache directory path
      id: yarn-cache-path
      run: echo "path=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash
      if: ${{ inputs.node-version-file }}
    - name: Cache Yarn global dependencies
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ${{ steps.yarn-cache-path.outputs.path }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
      if: ${{ inputs.node-version-file }}

    # Ref: https://github.com/streamlit/streamlit/blob/52736534b6488da3bcb0c9d8bba855855a963678/.github/actions/make_init/action.yml#L32-L45
    - name: Install `protoc` binary
      run: |
        PROTOC_VERSION=26.1
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
        sudo unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local bin/protoc
        sudo unzip -o protoc-${PROTOC_VERSION}-linux-x86_64.zip -d /usr/local 'include/*'
        sudo ln -s /usr/local/bin/protoc /usr/bin/protoc
        # Print out your System's protoc version:
        protoc --version
        rm protoc-${PROTOC_VERSION}-linux-x86_64.zip
      shell: bash
      if: ${{ inputs.protoc == 'true' }}

    - name: Set up Python packages
      run: make venv
      shell: bash
      if: ${{ inputs.python-version-file }}

    - name: Set up Node packages
      run: make node_modules
      shell: bash
      if: ${{ inputs.node-version-file && inputs.install-node-modules == 'true' }}
