import React from "react";
import sampleAppManifests from "../sample-app-manifests.json"; // This file is generated by bin/gen-sample-app-manifests-json.ts at build time.
import { Link } from "react-router-dom";
import { useSampleAppId, URL_SEARCH_KEY_SAMPLE_APP_ID } from "../router";

interface SampleAppMenuProps {}
function SampleAppMenu(props: SampleAppMenuProps) {
  const sampleAppId = useSampleAppId();

  return (
    <ol>
      {sampleAppManifests.map((sampleAppManifest) => (
        <li key={sampleAppManifest.id}>
          <Link
            to={{
              search: `${URL_SEARCH_KEY_SAMPLE_APP_ID}=${sampleAppManifest.id}`,
            }}
          >
            {sampleAppId === sampleAppManifest.id && "* "}
            {sampleAppManifest.title}
          </Link>
        </li>
      ))}
    </ol>
  );
}

export default SampleAppMenu;
