[project]
name = "stlite-lib"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
authors = [
    {name = "Yuichiro Tachibana (Tsuchiya)", email = "t.yic.yt@gmail.com"},
]
license = {text = "Apache-2.0"}
dependencies = [
    "pyodide-http>=0.2.1",
]

[tool.uv]
dev-dependencies = [
    "matplotlib>=3.9.2",
    "pandas-stubs>=2.2.3.241009",
    "pyodide-py>=0.27.6",
    "pyright>=1.1.384",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0",
    "requests>=2.32.3",
    "ruff>=0.6.9",
    "streamlit-folium>=0.25.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
extend-select = ["I"]

[tool.pyright]
include = ["stlite_lib"]
extraPaths = ["../../../../streamlit/lib"]

[tool.pytest.ini_options]
pythonpath = "../../../../streamlit/lib"
testpaths = [
    "stlite_lib_tests",  # To import the `tests` module in the `streamlit/lib` directory, use a different name for a test directory.
]
