import { useSearchParams } from "react-router-dom";
import sampleAppManifests from "./sample-app-manifests.json"; // This file is generated by bin/gen-sample-app-manifests-json.ts at build time.

export const URL_SEARCH_KEY_SAMPLE_APP_ID = "sampleAppId";

export function useSampleAppId(): string | null {
  const [searchParams, setSearchParams] = useSearchParams();
  const sampleAppId = searchParams.get(URL_SEARCH_KEY_SAMPLE_APP_ID);

  if (sampleAppId == null) {
    return null;
  }

  if (!sampleAppManifests.find((m) => m.id === sampleAppId)) {
    setSearchParams((curParams) => {
      const newParams = new URLSearchParams();
      curParams.forEach((value, key) => {
        if (key === URL_SEARCH_KEY_SAMPLE_APP_ID) {
          return;
        }
        newParams.append(key, value);
      });
      return newParams;
    });
    return null;
  }

  return sampleAppId;
}
