inputs:
  key:
    required: true
  name:
    required: true
  input-path:
    required: true

runs:
  using: "composite"
  steps:
    - name: Stage the files
      id: stage-files
      shell: bash
      run: |
        if [[ "${{ inputs.input-path }}" == *.tgz ]]; then
          filename=$(basename "${{ inputs.input-path }}")
          package_dir="$RUNNER_TEMP/package"
          package_path="$package_dir/$filename"
          files_dir="$RUNNER_TEMP/files"
          mkdir -p $package_dir $files_dir
          cp "${{ inputs.input-path }}" $package_dir
          tar -xzf "$package_path" -C $files_dir

          echo "PACKAGE_FILENAME=$package_path" >> $GITHUB_OUTPUT
          echo "FILES_DIR_PATH=$files_dir" >> $GITHUB_OUTPUT
        elif [[ -d "${{ inputs.input-path }}" ]]; then
          dir_name=$(basename "${{ inputs.input-path }}")
          files_dir="$RUNNER_TEMP/files"
          package_dir="$RUNNER_TEMP/package"
          mkdir -p $files_dir $package_dir
          cp -r "${{ inputs.input-path }}" $files_dir
          package_path="$package_dir/$dir_name.tgz"
          tar -czf "$package_path" -C $files_dir .

          echo "PACKAGE_FILENAME=$package_path" >> $GITHUB_OUTPUT
          echo "FILES_DIR_PATH=$files_dir" >> $GITHUB_OUTPUT
        fi
    - name: Create the stats JSON
      id: create-stats-json
      shell: bash
      run: |
        export NAME="${{ inputs.name }}"
        export PACKAGE_FILENAME=$(basename "${{ steps.stage-files.outputs.PACKAGE_FILENAME }}")
        export PACKAGE_SIZE_KIB=$(du -k "${{ steps.stage-files.outputs.PACKAGE_FILENAME }}" | cut -f1)
        export PACKAGE_FILES_TREE=$(tree "${{ steps.stage-files.outputs.FILES_DIR_PATH }}")

        output_filename="npm-package-stats.${{ inputs.key }}.json"
        output_filepath="$RUNNER_TEMP/$output_filename"

        jq -n \
          '{
            "name": env.NAME,
            "package": {
              "filename": env.PACKAGE_FILENAME,
              "sizeKib": env.PACKAGE_SIZE_KIB | tonumber
            },
            "files": {
              "tree": env.PACKAGE_FILES_TREE
            }
          }' > $output_filepath

        echo "OUTPUT_FILEPATH=$output_filepath" >> "$GITHUB_OUTPUT"
        echo "OUTPUT_FILENAME=$output_filename" >> "$GITHUB_OUTPUT"

    - name: Preview the JSON
      shell: bash
      run: cat ${{ steps.create-stats-json.outputs.OUTPUT_FILEPATH }}

    - name: Upload the JSON file as an artifact
      uses: actions/upload-artifact@v4
      if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
      with:
        path: ${{ steps.create-stats-json.outputs.OUTPUT_FILEPATH }}
        name: ${{ steps.create-stats-json.outputs.OUTPUT_FILENAME }}

    - run: |
        cd "$RUNNER_TEMP"
        npm install jszip
      shell: bash
    - name: Gather JSON files for this commit
      uses: actions/github-script@v6
      with:
        script: |
          process.chdir(process.env.RUNNER_TEMP)

          const jszip = require('jszip');

          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
          });

          const filteredArtifacts = artifacts.data.artifacts.filter(artifact =>
            artifact.name.match(/^npm-package-stats\..+\.json$/)
          );

          const artifactContents = await Promise.all(
            filteredArtifacts.map(async (artifact) => {
              const downloadResponse = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
                archive_format: 'zip',
              });

              const artifactZip = await downloadResponse.data;
              const zip = await jszip.loadAsync(artifactZip);
              const artifactFile = Object.values(zip.files)[0];
              const artifactContent = await artifactFile.async('string');

              return JSON.parse(artifactContent);
            })
          );

          console.log('Artifact contents:');
          console.log(JSON.stringify(artifactContents, null, 2));

    - name: Post a message to Pull Request threads
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        CURRENT_COMMIT_SHA=${{ github.sha }}

        PR_IDS=$(gh pr list --search "$CURRENT_COMMIT_SHA" --state open --json number --jq '.[].number')

        for PR_ID in $PR_IDS
        do
          echo "Post a message to ${PR_ID}"
        done
