[tool.poetry]
name = "stlite-tornado"
version = "0.1.0"
description = ""
authors = ["Yuichiro Tachibana (Tsuchiya) <t.yic.yt@gmail.com>"]
license = "Apache-2.0"
packages = [
    { include = "tornado" },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
# It is necessary to specify numpy and pandas versions for Poetry to resolve the package versions correctly and avoid errors.
numpy = "^1.21.0"
pandas = "^1.4.0"
streamlit = "1.10.0"
requests = "^2.28.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
