"""Durable Object deployment: one resident Streamlit runtime for all requests.

Plain Workers fan requests out across isolates, so a WebSocket session and the
HTTP requests it spawns (media, health) can land on different copies of the
runtime — each booting independently and holding its own session state. Routing
everything through a single named Durable Object instance gives every request
the same resident runtime: one cold boot is shared by all visitors, sessions
survive WebSocket reconnects, and in-memory media is served by the isolate that
registered it.

This does not make the runtime permanent: Cloudflare evicts idle Durable
Objects just like idle Workers, and WebSocket Hibernation cannot preserve the
Python runtime's in-memory state, so the first request after an idle period
still pays the cold boot.
"""

import logging

from workers import DurableObject, Response, WorkerEntrypoint

from stlite_cloudflare.entry import handle_request

_LOGGER = logging.getLogger(__name__)

# One Streamlit server per Worker; every visitor shares it (matching Streamlit's
# own model of one server process serving many sessions), so the instance name
# is a constant rather than derived from the request.
_INSTANCE_NAME = "streamlit"


class StliteServer(DurableObject):
    async def fetch(self, request):
        return await handle_request(self.env, request)


class Default(WorkerEntrypoint):
    async def fetch(self, request):
        namespace = getattr(self.env, "STLITE_SERVER", None)
        if namespace is None:
            _LOGGER.error("The STLITE_SERVER Durable Object binding is missing")
            return Response(
                "The STLITE_SERVER Durable Object binding is missing. The "
                "wrangler.jsonc generated by `stlite-cloudflare build "
                "--durable-object` declares it; a custom config must keep the "
                "binding and its migration.",
                status=500,
                headers={"content-type": "text/plain; charset=utf-8"},
            )
        stub = namespace.getByName(_INSTANCE_NAME)
        # Forward the raw JS request so the WebSocket upgrade (the 101 response
        # carrying `webSocket`) passes through the stub untouched.
        return await stub.fetch(request.js_object)
