"""The default deployment: one resident Streamlit runtime for all requests.

Plain Workers fan requests out across isolates, so a WebSocket session and the
HTTP requests whose state belongs to the runtime serving it — media fetches
and file uploads — can land on different copies of the runtime, each booting
independently with its own session state. Routing everything through a single
named Durable Object instance gives every request the same resident runtime:
one cold boot is shared by all visitors, sessions survive WebSocket
reconnects, uploads land in the runtime that will read them, and in-memory
media is served by the isolate that registered it. This is why the build
defaults to this mode; --plain-worker opts out for read-only, memory-heavy
apps (see the README for what that gives up).

This does not make the runtime permanent: Cloudflare evicts idle Durable
Objects just like idle Workers, and WebSocket Hibernation cannot preserve the
Python runtime's in-memory state, so the first request after an idle period
still pays the cold boot.

The concentration also cuts the other way on memory: the single instance
carries the union of every visited page's imports and every session's media
inside one 128 MB isolate, where the plain-Worker fan-out spreads that load
across isolates. Apps that run near the ceiling (e.g. the hello sample's
Animation demo, whose script run accumulates ~100 frames in Streamlit's
in-memory media storage) can exceed it here while squeaking by on plain
Workers; the platform resets the instance ("Durable Object's isolate exceeded
its memory limit"), which recovers on the next request but aborts the session
that tripped it. Offloading media bytes out of isolate memory (Cache API or
R2-backed storage instead of MemoryMediaFileStorage) is the natural next step
if this bites.
"""

import logging

from workers import DurableObject, Response, WorkerEntrypoint

from stlite_cloudflare.entry import handle_request

_LOGGER = logging.getLogger(__name__)

# One Streamlit server per Worker; every visitor shares it (matching Streamlit's
# own model of one server process serving many sessions), so the instance name
# is a constant rather than derived from the request.
_INSTANCE_NAME = "streamlit"


class StliteServer(DurableObject):
    async def fetch(self, request):
        return await handle_request(self.env, request, mirror_media=False)


class Default(WorkerEntrypoint):
    async def fetch(self, request):
        namespace = getattr(self.env, "STLITE_SERVER", None)
        if namespace is None:
            _LOGGER.error("The STLITE_SERVER Durable Object binding is missing")
            return Response(
                "The STLITE_SERVER Durable Object binding is missing. The "
                "wrangler.jsonc generated by `stlite-cloudflare "
                "build` declares it by default; a custom config must keep the "
                "binding and its migration.",
                status=500,
                headers={"content-type": "text/plain; charset=utf-8"},
            )
        stub = namespace.getByName(_INSTANCE_NAME)
        # Forward via the raw JS stub, not the SDK's fetcher wrapper: the
        # wrapper routes through pyfetch, which puts an AbortController on the
        # subrequest and aborts it when the Python response wrapper is
        # garbage-collected — killing the proxied WebSocket mid-session
        # (observed on the edge as `/_stcore/stream - Canceled` after the
        # session had already started). The raw fetch hands the upgrade
        # response (and its `webSocket`) back untouched.
        raw_stub = getattr(stub, "_binding", stub)
        return await raw_stub.fetch(request.js_object)
