"""Boot-time installer for the packaged Python runtime.

The Worker script ships only ``stlite_cloudflare`` and the workers SDK; the
rest of the runtime (streamlit, stlite_lib, and their dependency closure) is
packed into a static asset, because static assets don't count against
Cloudflare's Worker script-size limit (3/10 MiB gzip — far below the ~14 MiB
this closure gzips to). At cold start the tarball is fetched through the
assets binding (served same-colo) and extracted into the in-memory filesystem
before anything imports streamlit.
"""

import importlib
import io
import sys
import tarfile
import tempfile
from pathlib import Path
from typing import Any

PACKAGES_ASSET_PATH = "/_stlite/python-modules.tar.gz"
_TARGET = Path(tempfile.gettempdir()) / "stlite-python-modules"
_installed = False


async def ensure_packages(env: Any) -> None:
    """Fetch and extract the packaged runtime once per isolate.

    Callers must serialize concurrent invocations (runtime.py's single-flight
    init task does); this function itself only guards against repeat calls.
    """
    global _installed
    if _installed:
        return

    assets = getattr(env, "ASSETS", None)
    if assets is None:
        raise RuntimeError(
            "The ASSETS binding is missing. The wrangler.jsonc generated by "
            "`stlite-cloudflare build` declares it; a custom config must keep "
            "the assets binding so the runtime packages can load at startup."
        )
    response = await assets.fetch(f"https://assets.internal{PACKAGES_ASSET_PATH}")
    if response.status != 200:
        raise RuntimeError(
            f"Failed to load {PACKAGES_ASSET_PATH} from the assets binding "
            f"(HTTP {response.status})."
        )
    # The binding returns the workers SDK's Response, a pyodide FetchResponse
    # subclass whose bytes() yields Python bytes directly.
    data = await response.bytes()

    # The assets layer may serve the .gz body either raw or transparently
    # decoded depending on negotiation; sniff the magic bytes rather than
    # trusting the file extension.
    mode = "r:gz" if data[:2] == b"\x1f\x8b" else "r:"
    _TARGET.mkdir(parents=True, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(data), mode=mode) as tar:
        tar.extractall(_TARGET, filter="data")
    sys.path.insert(0, str(_TARGET))
    importlib.invalidate_caches()
    _installed = True
