"""Boot-time installer for the packaged Python runtime.

The Worker script ships only ``stlite_cloudflare``, the workers SDK, and the
native-extension packages that must live on a read-only filesystem; the pure
Python runtime ships as static assets, because assets don't count against
Cloudflare's Worker script-size limit. At cold start:

- ``python-modules.zip`` (the libraries) goes onto sys.path as-is, imported
  via zipimport — the modules never occupy the in-memory filesystem and
  decompress per-import, keeping the isolate's memory footprint down.
- ``extracted-modules.tar.gz`` (the user's app package plus anything
  zipimport can't serve, e.g. namespace packages) is extracted to real files.
"""

import asyncio
import sys
from pathlib import Path
from typing import Any

PACKAGES_ZIP_ASSET_PATH = "/_stlite/python-modules.zip"
EXTRACTED_ARCHIVE_ASSET_PATH = "/_stlite/extracted-modules.tar.gz"
# Keep this module inert at import time (it loads during the Worker's startup
# phase): fixed paths under Pyodide's in-memory /tmp instead of a
# tempfile.gettempdir() probe, and the heavier stdlib imports live inside
# ensure_packages().
_ZIP_TARGET = Path("/tmp/stlite-python-modules.zip")
_EXTRACT_TARGET = Path("/tmp/stlite-extracted-modules")
_installed = False


async def ensure_packages(env: Any) -> None:
    """Fetch and activate the packaged runtime once per isolate.

    Callers must serialize concurrent invocations (runtime.py's single-flight
    init task does); this function itself only guards against repeat calls.
    """
    global _installed
    if _installed:
        return

    import importlib.util
    import io
    import tarfile

    if importlib.util.find_spec("streamlit") is not None:
        # A --bundled-runtime build: the whole runtime already ships in the
        # script's python_modules, so there is nothing to fetch. Bundling
        # everything needs Cloudflare's planned 64 MB-uncompressed script
        # limit (https://github.com/cloudflare/workers-py/issues/156); the
        # asset-loading path below is the default until that ships.
        _installed = True
        return

    assets = getattr(env, "ASSETS", None)
    if assets is None:
        raise RuntimeError(
            "The ASSETS binding is missing. The wrangler.jsonc generated by "
            "`stlite-cloudflare build` declares it; a custom config must keep "
            "the assets binding so the runtime packages can load at startup."
        )

    zip_data, extracted_data = await asyncio.gather(
        _fetch_asset(assets, PACKAGES_ZIP_ASSET_PATH),
        _fetch_asset(assets, EXTRACTED_ARCHIVE_ASSET_PATH),
    )
    _ZIP_TARGET.parent.mkdir(parents=True, exist_ok=True)
    _ZIP_TARGET.write_bytes(zip_data)
    # The assets layer may serve the .gz body either raw or transparently
    # decoded depending on negotiation; sniff the magic bytes rather than
    # trusting the file extension.
    mode = "r:gz" if extracted_data[:2] == b"\x1f\x8b" else "r:"
    _EXTRACT_TARGET.mkdir(parents=True, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(extracted_data), mode=mode) as tar:
        tar.extractall(_EXTRACT_TARGET, filter="data")

    sys.path.insert(0, str(_EXTRACT_TARGET))
    sys.path.insert(0, str(_ZIP_TARGET))
    importlib.invalidate_caches()
    _installed = True


async def _fetch_asset(assets: Any, asset_path: str) -> bytes:
    response = await assets.fetch(f"https://assets.internal{asset_path}")
    if response.status != 200:
        raise RuntimeError(
            f"Failed to load {asset_path} from the assets binding "
            f"(HTTP {response.status})."
        )
    # The binding returns the workers SDK's Response, a pyodide FetchResponse
    # subclass whose bytes() yields Python bytes directly.
    return await response.bytes()
