name: Cloudflare Pages Deploy

on:
  workflow_run:
    workflows: ["Test, Build, and Publish"]
    types:
      - completed

permissions:
  contents: read

jobs:
  get-deploy-info:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      branch: ${{ steps.deploy-info.outputs.branch }}
      commit-hash: ${{ steps.deploy-info.outputs.commit-hash }}
    steps:
      - name: Download deployment info
        uses: actions/download-artifact@v4
        with:
          name: deploy-info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Read deployment info
        id: deploy-info
        run: |
          echo "branch=$(cat branch)" >> $GITHUB_OUTPUT
          echo "commit-hash=$(cat commit-hash)" >> $GITHUB_OUTPUT

  deploy-sharing:
    needs: get-deploy-info
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy @stlite/sharing to Cloudflare Pages
    outputs:
      url: ${{ steps.deploy.outputs.pages-deployment-alias-url }}
    steps:
      - run: mkdir -p ${{ runner.temp }}/artifacts/

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: stlite-sharing
          path: ${{ runner.temp }}/artifacts/sharing
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Deploy
        uses: cloudflare/wrangler-action@392082e81ffbcb9ebdde27400634aa004b35ea37
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ runner.temp }}/artifacts/sharing --project-name=stlite-sharing --branch=${{ needs.get-deploy-info.outputs.branch }} --commit-hash=${{ needs.get-deploy-info.outputs.commit-hash }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  deploy-sharing-editor:
    needs: [get-deploy-info]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy @stlite/sharing-editor to Cloudflare Pages
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: stlite-sharing-editor
          path: ${{ runner.temp }}/artifacts/sharing-editor
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Inject SHARING_APP_URL
        run: |
          echo "${{ needs.deploy-sharing.outputs.url }}" > ${{ runner.temp }}/artifacts/sharing-editor/SHARING_APP_URL

      - name: Deploy
        uses: cloudflare/wrangler-action@392082e81ffbcb9ebdde27400634aa004b35ea37
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ runner.temp }}/artifacts/sharing-editor --project-name=stlite-sharing-editor --branch=${{ needs.get-deploy-info.outputs.branch }} --commit-hash=${{ needs.get-deploy-info.outputs.commit-hash }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
