name: Create New Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      force-publish:
        description: 'Force publish even if there are no changes'
        required: false
        default: false
        type: boolean

env:
  node-version-file: ".nvmrc"

jobs:
  new-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false
          fetch-depth: 0

      - uses: ./.github/actions/init-all
        with:
          node-version-file: ${{ env.node-version-file }}
          protoc: false

      - name: Configure Git
        run: |
            git config --global user.name 'Yuichiro Tachibana (Tsuchiya)'
            git config --global user.email 't.yic.yt@gmail.com'

      - name: Version packages
        run: yarn new-version ${{ github.event.inputs.version }} --yes ${{ github.event.inputs.force-publish == 'true' && '--force-publish' || '' }} --no-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: |
            git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push --follow-tags origin HEAD
